/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source, please visit the GitHub repository of this plugin
*/

'use strict';

var obsidian = require('obsidian');

const ANKI_CONNECT_URL = 'http://127.0.0.1:8765';
const MANAGED_NOTE_TAG = 'obsidian_simple_anki_sync_created';
async function sendRequest(action, params = {}) {
    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();
        xhr.addEventListener('error', () => reject(new Error('Failed to issue request to AnkiConnect. Is Anki running?')));
        xhr.addEventListener('load', () => {
            try {
                const resp = JSON.parse(xhr.responseText);
                if (resp.error) {
                    console.error('AnkiConnect Error:', resp.error);
                    reject(new Error(`AnkiConnect error: ${resp.error}`));
                }
                else {
                    resolve(resp.result);
                }
            }
            catch (err) {
                console.error('Failed to parse AnkiConnect response:', err);
                reject(new Error('Failed to parse AnkiConnect response.'));
            }
        });
        xhr.open('POST', ANKI_CONNECT_URL);
        xhr.send(JSON.stringify({ action, version: 6, params }));
    });
}
class AnkiService {
    constructor(app) {
        this.app = app;
    }
    async verifyConnection() {
        try {
            await sendRequest('requestPermission');
            const decks = await sendRequest('deckNames');
            return Array.isArray(decks);
        }
        catch (err) {
            new obsidian.Notice('AnkiConnect connection failed. Is Anki open with AnkiConnect installed?');
            console.error('verifyConnection error:', err);
            return false;
        }
    }
    async fetchDecks() {
        try {
            return await sendRequest('deckNames');
        }
        catch (err) {
            new obsidian.Notice('Failed to retrieve deck list from Anki.');
            console.error(err);
            return [];
        }
    }
    async createDeck(name) {
        try {
            await sendRequest('createDeck', { deck: name });
        }
        catch (err) {
            if (err instanceof Error && err.message.includes('deck already exists'))
                return;
            new obsidian.Notice(`Could not create deck "${name}".`);
            console.error(err);
        }
    }
    async addNote(deck, model, fields, tags = []) {
        try {
            const allTags = [...tags, MANAGED_NOTE_TAG];
            const result = await sendRequest('addNote', {
                note: { deckName: deck, modelName: model, fields, tags: allTags },
            });
            if (typeof result === 'number')
                return result;
            new obsidian.Notice('AnkiConnect did not return a valid note ID.');
            return null;
        }
        catch (err) {
            new obsidian.Notice(`Failed to add note: ${err instanceof Error ? err.message : err}`);
            console.error(err);
            return null;
        }
    }
    async updateNote(noteId, fields) {
        try {
            await sendRequest('updateNoteFields', {
                note: { id: noteId, fields },
            });
            // Ensure our tag persists
            const infos = await this.fetchNotesInfo([noteId]);
            if (infos[0] && !infos[0].tags.includes(MANAGED_NOTE_TAG)) {
                await sendRequest('updateNoteTags', {
                    note: noteId,
                    tags: [...infos[0].tags, MANAGED_NOTE_TAG],
                });
            }
        }
        catch (err) {
            new obsidian.Notice(`Failed to update note ${noteId}: ${err}`);
            console.error(err);
        }
    }
    async deleteNotes(ids) {
        if (!ids.length)
            return;
        try {
            await sendRequest('deleteNotes', { notes: ids });
            new obsidian.Notice(`Deleted ${ids.length} note(s) from Anki.`);
        }
        catch (err) {
            new obsidian.Notice(`Could not delete notes: ${err}`);
            console.error(err);
        }
    }
    async fetchNotesInfo(ids) {
        if (!ids.length)
            return [];
        try {
            return await sendRequest('notesInfo', { notes: ids });
        }
        catch (err) {
            new obsidian.Notice('Failed to fetch note info from Anki.');
            console.error(err);
            return [];
        }
    }
    async findManagedNotes() {
        try {
            const result = await sendRequest('findNotes', { query: `tag:${MANAGED_NOTE_TAG}` });
            return Array.isArray(result) ? result : [];
        }
        catch (err) {
            new obsidian.Notice('Could not find managed notes in Anki.');
            console.error(err);
            return [];
        }
    }
    async changeDeck(cardIds, deckName) {
        try {
            const ok = await sendRequest('changeDeck', { cards: cardIds, deck: deckName });
            return ok === true;
        }
        catch (err) {
            new obsidian.Notice(`Failed to move card(s): ${err}`);
            console.error(err);
            return false;
        }
    }
    async fetchCardInfo(cardIds) {
        try {
            return await sendRequest('cardsInfo', { cards: cardIds });
        }
        catch (err) {
            new obsidian.Notice(`cardsInfo error: ${err}`);
            console.error(err);
            return [];
        }
    }
    async storeMediaBase64(filename, data) {
        try {
            const result = await sendRequest('storeMediaFile', {
                filename,
                data, // the base64 payload
            });
            return typeof result === 'string' ? result : filename;
        }
        catch (err) {
            new obsidian.Notice(`Failed to store media "${filename}": ${err}`);
            console.error(err);
            return null;
        }
    }
    resolveAbsolutePath(vaultPath) {
        const file = this.app.vault.getAbstractFileByPath(vaultPath);
        if (file instanceof obsidian.TFile) {
            // @ts-ignore
            return this.app.vault.adapter.getFullPath(file.path);
        }
        console.warn(`File not found in vault: ${vaultPath}`);
        return null;
    }
}

const DEFAULT_SETTINGS = {
    enableAnswerToggle: true,
    defaultCollapsed: true,
};
class SimpleAnkiSyncSettingTab extends obsidian.PluginSettingTab {
    constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
    }
    display() {
        const { containerEl } = this;
        containerEl.empty();
        containerEl.createEl('h2', { text: 'Simple Anki Sync' });
        new obsidian.Setting(containerEl)
            .setName('Enable answer table toggles')
            .setDesc('Allow collapsing/expanding single-column Anki tables in preview and source view.')
            .addToggle((toggle) => toggle
            .setValue(this.plugin.settings.enableAnswerToggle)
            .onChange(async (value) => {
            this.plugin.settings.enableAnswerToggle = value;
            await this.plugin.saveSettings();
            this.plugin.applyRowToggleSettings();
            this.display();
        }));
        new obsidian.Setting(containerEl)
            .setName('Collapse tables by default')
            .setDesc('When enabled, newly rendered single-column Anki tables start collapsed.')
            .addToggle((toggle) => {
            toggle
                .setValue(this.plugin.settings.defaultCollapsed)
                .setDisabled(!this.plugin.settings.enableAnswerToggle)
                .onChange(async (value) => {
                this.plugin.settings.defaultCollapsed = value;
                await this.plugin.saveSettings();
                this.plugin.applyRowToggleSettings();
            });
        });
    }
}

const STYLE_ID = 'single-column-toggle-table-style';
const DATA_APPLIED = 'rowToggleApplied';
const CLASS_TABLE = 'row-toggle-table';
const CLASS_COLLAPSED = 'is-collapsed';
const CLASS_TRIGGER = 'row-toggle-trigger';
const CLASS_BUTTON = 'row-toggle-button';
const CLASS_TEXT = 'row-toggle-text';
const CLASS_EDITING = 'is-editing';
const MARKDOWN_VIEW_SELECTOR = '.markdown-preview-view, .markdown-source-view.mod-cm6';
const EDITABLE_CELL_SELECTOR = 'td, th';
const TOGGLE_LABEL = 'Toggle answer row';
const STYLES = `
.markdown-rendered table.${CLASS_TABLE} .${CLASS_TRIGGER} {
  position: relative;
  padding-left: 1.2em !important;
}

/* Reading view can override table cell padding; enforce spacing there only. */
.markdown-reading-view .markdown-rendered table.${CLASS_TABLE} .${CLASS_TRIGGER} {
  padding-left: 1.2em !important;
}

.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} .${CLASS_TRIGGER} {
  position: relative;
  padding-left: 1.2em;
}

.markdown-rendered table.${CLASS_TABLE} .${CLASS_BUTTON} {
  all: unset;
  position: absolute;
  top: 50%;
  left: 0.35em;
  transform: translateY(-50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 1.1em;
  height: 1.1em;
  line-height: 1;
  cursor: pointer;
  z-index: 1;
}

.markdown-rendered table.${CLASS_TABLE} .${CLASS_TEXT} {
  display: block;
  padding-left: 0 !important;
}

.markdown-rendered table.${CLASS_TABLE} .${CLASS_TEXT}:empty::before {
  content: "\\00a0";
}

.markdown-rendered table.${CLASS_TABLE} td:empty::before {
  content: "\\00a0";
}

.markdown-reading-view .markdown-rendered table.${CLASS_TABLE} .${CLASS_TEXT} {
  padding-left: 0 !important;
}

.markdown-rendered table.${CLASS_TABLE} .${CLASS_BUTTON}::before {
  content: ">";
}

.markdown-rendered table.${CLASS_TABLE}:not(.${CLASS_COLLAPSED}) .${CLASS_BUTTON}::before {
  content: "v";
}

.markdown-rendered table.${CLASS_TABLE} .${CLASS_BUTTON}:focus-visible {
  outline: 1px solid var(--text-accent, currentColor);
  border-radius: var(--radius-s, 4px);
  outline-offset: 2px;
}

.markdown-rendered table.${CLASS_TABLE}.${CLASS_COLLAPSED} tbody tr {
  display: none;
}

.markdown-rendered table.${CLASS_TABLE} th,
.markdown-rendered table.${CLASS_TABLE} td,
.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} th,
.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} td {
  overflow-wrap: anywhere;
}

.markdown-rendered .table-wrapper:has(table.${CLASS_TABLE}),
.markdown-source-view.mod-cm6 .cm-table-widget:has(table.${CLASS_TABLE}) {
  overflow-x: hidden;
  overflow-x: clip;
}

.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} .${CLASS_TEXT} {
  padding-left: 0;
}

.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} th .cm-line {
  padding-left: 0 !important;
}

.markdown-source-view.mod-cm6 .cm-table-widget table.${CLASS_TABLE} th.${CLASS_EDITING} .cm-line {
  padding-left: 0 !important;
}
`;
const stopEvent = (event) => {
    event.preventDefault();
    event.stopPropagation();
};
class TableToggleManager {
    constructor(settings) {
        this.observer = null;
        this.settings = settings;
    }
    updateSettings(settings) {
        this.settings = settings;
    }
    registerMarkdownPostProcessor(plugin) {
        plugin.registerMarkdownPostProcessor((el) => this.decorateTables(el));
    }
    onLoad() {
        this.startDomObserver();
        this.applySettings();
    }
    onUnload() {
        if (this.observer) {
            this.observer.disconnect();
            this.observer = null;
        }
        this.removeToggleDecorations(document.body);
        this.removeStyles();
    }
    applySettings() {
        if (!document.body)
            return;
        if (this.settings.enableAnswerToggle) {
            this.injectStyles();
            this.decorateTables(document.body);
            this.setAllTablesCollapsed(this.settings.defaultCollapsed, document.body);
        }
        else {
            this.removeToggleDecorations(document.body);
            this.removeStyles();
        }
    }
    setTablesCollapsedInScope(container, collapsed) {
        this.decorateTables(container);
        this.setAllTablesCollapsed(collapsed, container);
    }
    injectStyles() {
        if (document.getElementById(STYLE_ID)) {
            return;
        }
        const styleElement = document.createElement('style');
        styleElement.id = STYLE_ID;
        styleElement.textContent = STYLES;
        document.head.appendChild(styleElement);
    }
    removeStyles() {
        const styleElement = document.getElementById(STYLE_ID);
        if (styleElement) {
            styleElement.remove();
        }
    }
    startDomObserver() {
        if (!document.body || this.observer) {
            return;
        }
        this.observer = new MutationObserver((mutations) => {
            if (!this.settings.enableAnswerToggle) {
                return;
            }
            for (const mutation of mutations) {
                for (const node of Array.from(mutation.addedNodes)) {
                    this.decorateTables(node);
                }
            }
        });
        this.observer.observe(document.body, {
            childList: true,
            subtree: true,
        });
    }
    decorateTables(container) {
        if (!this.settings.enableAnswerToggle) {
            return;
        }
        if (!(container instanceof HTMLElement)) {
            return;
        }
        const tables = container instanceof HTMLTableElement
            ? [container]
            : Array.from(container.querySelectorAll('table'));
        for (const table of tables) {
            if (table instanceof HTMLTableElement) {
                this.decorateTable(table);
            }
        }
    }
    decorateTable(table) {
        var _a, _b, _c, _d;
        if (table.dataset[DATA_APPLIED] === 'true') {
            return;
        }
        if (!this.isInsideMarkdownView(table) || !this.isTargetTable(table)) {
            return;
        }
        const headerCell = (_d = (_c = (_b = (_a = table.tHead) === null || _a === void 0 ? void 0 : _a.rows) === null || _b === void 0 ? void 0 : _b[0]) === null || _c === void 0 ? void 0 : _c.cells) === null || _d === void 0 ? void 0 : _d[0];
        if (!headerCell) {
            return;
        }
        table.dataset[DATA_APPLIED] = 'true';
        table.classList.add(CLASS_TABLE);
        headerCell.classList.add(CLASS_TRIGGER);
        headerCell.style.setProperty('padding-left', '1.2em', 'important');
        const textWrapper = this.wrapHeaderText(headerCell);
        textWrapper.style.setProperty('padding-left', '0', 'important');
        textWrapper.style.setProperty('margin-left', '0', 'important');
        textWrapper.style.setProperty('display', 'block', 'important');
        const toggleButton = this.createToggleButton();
        headerCell.insertBefore(toggleButton, textWrapper);
        this.ensureToggleSpacing(headerCell, textWrapper, toggleButton);
        const toggle = () => {
            this.setTableCollapsed(table, !table.classList.contains(CLASS_COLLAPSED));
        };
        toggleButton.addEventListener('click', (event) => {
            stopEvent(event);
            toggle();
        });
        toggleButton.addEventListener('pointerdown', stopEvent);
        toggleButton.addEventListener('mousedown', stopEvent);
        this.bindEditingState(table, headerCell);
        this.setTableCollapsed(table, this.settings.defaultCollapsed);
    }
    wrapHeaderText(cell) {
        const existing = cell.querySelector(`:scope > .${CLASS_TEXT}`);
        if (existing instanceof HTMLSpanElement) {
            return existing;
        }
        const wrapper = document.createElement('span');
        wrapper.className = CLASS_TEXT;
        while (cell.firstChild) {
            wrapper.appendChild(cell.firstChild);
        }
        cell.appendChild(wrapper);
        return wrapper;
    }
    unwrapHeaderText(cell) {
        const wrapper = cell.querySelector(`:scope > .${CLASS_TEXT}`);
        if (!(wrapper instanceof HTMLSpanElement)) {
            return;
        }
        while (wrapper.firstChild) {
            cell.insertBefore(wrapper.firstChild, wrapper);
        }
        wrapper.remove();
    }
    createToggleButton() {
        const button = document.createElement('button');
        button.type = 'button';
        button.className = CLASS_BUTTON;
        button.setAttribute('aria-label', TOGGLE_LABEL);
        button.setAttribute('aria-expanded', 'false');
        return button;
    }
    ensureToggleSpacing(headerCell, textWrapper, toggleButton) {
        // Only needed in reading view; preview is already correct.
        if (!headerCell.closest('.markdown-reading-view')) {
            return;
        }
        const applySpacing = () => {
            if (!headerCell.isConnected)
                return;
            const buttonRect = toggleButton.getBoundingClientRect();
            const textRect = textWrapper.getBoundingClientRect();
            if (buttonRect.width === 0 || textRect.width === 0)
                return;
            const fontSize = Number.parseFloat(getComputedStyle(headerCell).fontSize || '16');
            const desiredGapPx = fontSize * 0.25;
            const desiredLeft = buttonRect.right + desiredGapPx;
            const currentLeft = textRect.left;
            if (currentLeft >= desiredLeft - 0.5) {
                return;
            }
            const currentMargin = Number.parseFloat(getComputedStyle(textWrapper).marginLeft || '0');
            const delta = desiredLeft - currentLeft;
            const nextMargin = currentMargin + delta;
            textWrapper.style.setProperty('margin-left', `${nextMargin}px`, 'important');
        };
        requestAnimationFrame(applySpacing);
    }
    bindEditingState(table, headerCell) {
        const updateEditingState = () => {
            var _a;
            const active = document.activeElement instanceof HTMLElement ? document.activeElement : null;
            const activeCell = (_a = active === null || active === void 0 ? void 0 : active.closest(EDITABLE_CELL_SELECTOR)) !== null && _a !== void 0 ? _a : null;
            headerCell.classList.toggle(CLASS_EDITING, activeCell === headerCell);
        };
        table.addEventListener('focusin', updateEditingState);
        table.addEventListener('focusout', () => {
            setTimeout(updateEditingState, 0);
        });
    }
    setTableCollapsed(table, collapsed) {
        table.classList.toggle(CLASS_COLLAPSED, collapsed);
        const button = table.querySelector(`.${CLASS_BUTTON}`);
        if (button) {
            button.setAttribute('aria-expanded', String(!collapsed));
        }
    }
    setAllTablesCollapsed(collapsed, container) {
        const tables = Array.from(container.querySelectorAll(`table.${CLASS_TABLE}`));
        for (const table of tables) {
            this.setTableCollapsed(table, collapsed);
        }
    }
    removeToggleDecorations(container) {
        var _a, _b, _c, _d;
        if (!container) {
            return;
        }
        const tables = Array.from(container.querySelectorAll(`table.${CLASS_TABLE}`));
        for (const table of tables) {
            table.classList.remove(CLASS_TABLE, CLASS_COLLAPSED);
            delete table.dataset[DATA_APPLIED];
            const headerCell = (_d = (_c = (_b = (_a = table.tHead) === null || _a === void 0 ? void 0 : _a.rows) === null || _b === void 0 ? void 0 : _b[0]) === null || _c === void 0 ? void 0 : _c.cells) === null || _d === void 0 ? void 0 : _d[0];
            if (headerCell) {
                headerCell.classList.remove(CLASS_TRIGGER, CLASS_EDITING);
                const button = headerCell.querySelector(`.${CLASS_BUTTON}`);
                if (button) {
                    button.remove();
                }
                this.unwrapHeaderText(headerCell);
            }
        }
    }
    isInsideMarkdownView(table) {
        return Boolean(table.closest(MARKDOWN_VIEW_SELECTOR));
    }
    isTargetTable(table) {
        if (!table.tHead || table.tHead.rows.length !== 1) {
            return false;
        }
        const headRow = table.tHead.rows[0];
        if (headRow.cells.length !== 1) {
            return false;
        }
        const body = table.tBodies[0];
        if (!body || body.rows.length !== 1) {
            return false;
        }
        return body.rows[0].cells.length === 1;
    }
}

// Regex-Templates
const DECK_TAG = /#anki\/([^\s]+)/;
const NOTE_ID_COMMENT = /<!--ANKI_NOTE_ID:(\d+)-->/;
const NOTE_ID_COMMENT_GLOBAL = /<!--ANKI_NOTE_ID:(\d+)-->/g;
const IMAGE_EMBED = /!\[\[([^|\]\n]+)(?:\|(\d+))?\]\]/g;
const BLOCK_LATEX = /\$\$([\s\S]*?)\$\$/g;
const INLINE_LATEX = /(?<![\$\\])\$([^$]+?)(?<!\\)\$/g;
const DEFAULT_MODEL = 'Basic';
const EMPTY_ANKI_BLOCK = `|     |\n| --- |\n|     |`;
class SimpleAnkiSyncPlugin extends obsidian.Plugin {
    constructor() {
        super(...arguments);
        this.settings = DEFAULT_SETTINGS;
    }
    async onload() {
        console.log('Loading Simple Anki Sync Plugin');
        this.anki = new AnkiService(this.app);
        await this.loadSettings();
        this.tableToggle = new TableToggleManager(this.settings);
        this.tableToggle.registerMarkdownPostProcessor(this);
        this.tableToggle.onLoad();
        this.addSettingTab(new SimpleAnkiSyncSettingTab(this.app, this));
        this.addCommand({
            id: 'sync-current-file-with-anki',
            name: 'Sync current file with Anki',
            checkCallback: (checking) => {
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (view === null || view === void 0 ? void 0 : view.file) {
                    if (!checking)
                        this.syncFile(view.file);
                    return true;
                }
                return false;
            },
        });
        this.addCommand({
            id: 'sync-vault-with-anki',
            name: 'Sync entire vault with Anki',
            callback: async () => {
                await this.syncVault();
            },
        });
        this.addCommand({
            id: 'unsync-current-file-with-anki',
            name: 'Unsync current file with Anki',
            checkCallback: (checking) => {
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (view === null || view === void 0 ? void 0 : view.file) {
                    if (!checking)
                        this.unSyncFile(view.file);
                    return true;
                }
                return false;
            },
        });
        this.addCommand({
            id: 'collapse-anki-card-tables',
            name: 'Collapse all Anki card tables on page',
            checkCallback: (checking) => {
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (!view)
                    return false;
                if (checking)
                    return true;
                if (!this.settings.enableAnswerToggle) {
                    new obsidian.Notice('Answer table toggles are disabled in settings.');
                    return;
                }
                this.tableToggle.setTablesCollapsedInScope(view.contentEl, true);
            },
        });
        this.addCommand({
            id: 'expand-anki-card-tables',
            name: 'Expand all Anki card tables on page',
            checkCallback: (checking) => {
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (!view)
                    return false;
                if (checking)
                    return true;
                if (!this.settings.enableAnswerToggle) {
                    new obsidian.Notice('Answer table toggles are disabled in settings.');
                    return;
                }
                this.tableToggle.setTablesCollapsedInScope(view.contentEl, false);
            },
        });
        this.addCommand({
            id: 'insert-empty-anki-card',
            name: 'Insert empty Anki card block',
            checkCallback: (checking) => {
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (!view || !view.editor)
                    return false;
                if (checking)
                    return true;
                const editor = view.editor;
                editor.replaceRange(EMPTY_ANKI_BLOCK, editor.getCursor());
                if (this.settings.enableAnswerToggle) {
                    window.setTimeout(() => {
                        var _a;
                        (_a = this.tableToggle) === null || _a === void 0 ? void 0 : _a.setTablesCollapsedInScope(view.contentEl, false);
                    }, 0);
                }
                return;
            },
        });
        this.registerObsidianProtocolHandler('simple-anki-sync', this.handleCustomProtocol.bind(this));
    }
    async handleCustomProtocol(params) {
        if (params.action === 'simple-anki-sync') {
            const { file, noteId } = params;
            if (!file || !noteId)
                return;
            const abstractFile = this.app.vault.getAbstractFileByPath(file);
            if (!(abstractFile instanceof obsidian.TFile))
                return;
            const leaf = this.app.workspace.getLeaf(false);
            await leaf.openFile(abstractFile);
            const content = await this.app.vault.read(abstractFile);
            const lines = content.split('\n');
            const searchFor = `<!--ANKI_NOTE_ID:${noteId}-->`;
            const lineNumber = lines.findIndex(line => line.includes(searchFor));
            if (lineNumber !== -1) {
                // Find where the trailing Anki comment or `<br>` tags start, so we can place the cursor exactly there
                const line = lines[lineNumber];
                const match = line.match(/(?:<br\s*\/?>\s*)*<!--ANKI_NOTE_ID:\d+-->/i);
                const column = match ? match.index || 0 : 0;
                const view = this.app.workspace.getActiveViewOfType(obsidian.MarkdownView);
                if (view && view.editor) { // only if in edit mode
                    view.editor.setCursor(lineNumber, column);
                    view.editor.scrollIntoView({ from: { line: lineNumber, ch: 0 }, to: { line: lineNumber, ch: 0 } }, true);
                }
            }
        }
    }
    onunload() {
        var _a;
        console.log('Unloading Simple Anki Sync Plugin');
        (_a = this.tableToggle) === null || _a === void 0 ? void 0 : _a.onUnload();
    }
    async loadSettings() {
        this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    }
    async saveSettings() {
        await this.saveData(this.settings);
    }
    applyRowToggleSettings() {
        var _a, _b;
        (_a = this.tableToggle) === null || _a === void 0 ? void 0 : _a.updateSettings(this.settings);
        (_b = this.tableToggle) === null || _b === void 0 ? void 0 : _b.applySettings();
    }
    // Splits a table row into its cells
    splitTableRow(row) {
        const clean = row.trim().replace(/^\||\|$/g, '');
        const cells = [];
        let buf = '';
        let inBrackets = false; // [[...]]
        let inInlineMath = false; // $...$
        let inBlockMath = false; // $$...$$
        for (let i = 0; i < clean.length; i++) {
            if (!inInlineMath && clean.slice(i, i + 2) === '$$') {
                inBlockMath = !inBlockMath;
                buf += '$$';
                i++;
                continue;
            }
            if (!inBlockMath && clean[i] === '$') {
                inInlineMath = !inInlineMath;
                buf += '$';
                continue;
            }
            if (!inBrackets && clean.slice(i, i + 2) === '[[') {
                inBrackets = true;
                buf += '[[';
                i++;
                continue;
            }
            if (inBrackets && clean.slice(i, i + 2) === ']]') {
                inBrackets = false;
                buf += ']]';
                i++;
                continue;
            }
            const ch = clean[i];
            if (ch === '\\' && clean[i + 1] === '|') {
                buf += '|';
                i++;
                continue;
            }
            if (ch === '|' && !inBrackets && !inInlineMath && !inBlockMath) {
                cells.push(buf.trim());
                buf = '';
                continue;
            }
            buf += ch;
        }
        cells.push(buf.trim());
        return cells.filter((c) => c !== '' || cells.length === 1);
    }
    extractInlineNoteId(back) {
        const match = back.match(NOTE_ID_COMMENT);
        if (!match) {
            return { cleanedBack: back };
        }
        const noteId = parseInt(match[1], 10);
        const trailingPattern = new RegExp(`(?:<br\\s*\\/?>\\s*)*${NOTE_ID_COMMENT.source}\\s*$`, 'i');
        let cleanedBack = back;
        if (trailingPattern.test(cleanedBack)) {
            cleanedBack = cleanedBack.replace(trailingPattern, '');
            cleanedBack = cleanedBack.replace(/\s+$/, '');
        }
        else {
            const inlinePattern = new RegExp(NOTE_ID_COMMENT.source, 'g');
            cleanedBack = cleanedBack.replace(inlinePattern, '');
        }
        return { noteId, cleanedBack };
    }
    appendNoteIdToRow(row, noteId) {
        if (NOTE_ID_COMMENT.test(row)) {
            return row;
        }
        const match = row.match(/^(\s*\|)(.*)(\|\s*)$/);
        if (!match) {
            return row;
        }
        const [, left, cell, right] = match;
        const trimmedCell = cell.replace(/\s+$/, '');
        const spacer = trimmedCell.length ? '<br><br>' : '';
        const updatedCell = `${trimmedCell}${spacer}<!--ANKI_NOTE_ID:${noteId}-->`;
        return `${left}${updatedCell}${right}`;
    }
    stripNoteIdFromCell(cell, noteId) {
        if (!cell.includes('ANKI_NOTE_ID')) {
            return { updatedCell: cell, removed: false };
        }
        if (noteId && !cell.includes(`<!--ANKI_NOTE_ID:${noteId}-->`)) {
            return { updatedCell: cell, removed: false };
        }
        const idPattern = noteId
            ? `<!--ANKI_NOTE_ID:${noteId}-->`
            : NOTE_ID_COMMENT.source;
        const trailingPattern = new RegExp(`(?:<br\\s*\\/?>\\s*)*${idPattern}\\s*$`, 'i');
        let updatedCell = cell;
        if (trailingPattern.test(updatedCell)) {
            const trimmed = updatedCell.replace(trailingPattern, '').replace(/\s+$/, '');
            return { updatedCell: trimmed, removed: trimmed !== cell };
        }
        const inlinePattern = noteId
            ? new RegExp(`<!--ANKI_NOTE_ID:${noteId}-->`, 'g')
            : new RegExp(NOTE_ID_COMMENT.source, 'g');
        updatedCell = updatedCell.replace(inlinePattern, '');
        return { updatedCell, removed: updatedCell !== cell };
    }
    stripNoteIdFromLine(line, noteId) {
        if (!line.includes('ANKI_NOTE_ID')) {
            return { updatedLine: line, removed: false, removeLine: false };
        }
        const trimmed = line.trim();
        const linePattern = noteId
            ? new RegExp(`^<!--ANKI_NOTE_ID:${noteId}-->$`)
            : new RegExp(`^${NOTE_ID_COMMENT.source}$`);
        if (linePattern.test(trimmed)) {
            return { updatedLine: '', removed: true, removeLine: true };
        }
        const rowMatch = line.match(/^(\s*\|)(.*)(\|\s*)$/);
        if (rowMatch) {
            const [, left, cell, right] = rowMatch;
            const { updatedCell, removed } = this.stripNoteIdFromCell(cell, noteId);
            if (removed) {
                return {
                    updatedLine: `${left}${updatedCell}${right}`,
                    removed: true,
                    removeLine: false,
                };
            }
        }
        const inlinePattern = noteId
            ? new RegExp(`<!--ANKI_NOTE_ID:${noteId}-->`, 'g')
            : new RegExp(NOTE_ID_COMMENT.source, 'g');
        const updatedLine = line.replace(inlinePattern, '');
        return { updatedLine, removed: updatedLine !== line, removeLine: false };
    }
    // Parses the content of a file and extracts notes and deck name
    parseNotesFromContent(content, file) {
        var _a, _b;
        const tagMatch = content.match(DECK_TAG);
        const deckName = (_b = (_a = tagMatch === null || tagMatch === void 0 ? void 0 : tagMatch[1]) === null || _a === void 0 ? void 0 : _a.replace(/\//g, '::')) !== null && _b !== void 0 ? _b : null;
        const notes = [];
        const lines = content.split('\n');
        for (let i = 0; i < lines.length - 2; i++) {
            const h = lines[i];
            const sep = lines[i + 1];
            const d = lines[i + 2];
            if (h.trim().startsWith('|') &&
                sep.match(/^\|\s*-{3,}\s*\|$/) &&
                d.trim().startsWith('|')) {
                const headerCells = this.splitTableRow(h);
                const dataCells = this.splitTableRow(d);
                if (headerCells.length !== 1 || dataCells.length !== 1) {
                    i++;
                    continue;
                }
                const nextLine = lines[i + 3];
                if (nextLine === null || nextLine === void 0 ? void 0 : nextLine.trim().startsWith('|')) {
                    i++;
                    continue;
                }
                let existingId;
                let endLine = i + 2;
                const inlineId = this.extractInlineNoteId(dataCells[0]);
                dataCells[0] = inlineId.cleanedBack;
                if (inlineId.noteId) {
                    existingId = inlineId.noteId;
                }
                else {
                    const maybeComment = lines[i + 3];
                    const idMatch = maybeComment === null || maybeComment === void 0 ? void 0 : maybeComment.match(NOTE_ID_COMMENT);
                    if (idMatch) {
                        existingId = parseInt(idMatch[1], 10);
                        endLine = i + 3;
                    }
                }
                notes.push({
                    sourceId: `${file.path}-${i}`,
                    front: headerCells[0],
                    back: dataCells[0],
                    noteId: existingId,
                    startLine: i,
                    endLine,
                });
                i = endLine;
            }
        }
        return { notes, deckName };
    }
    async processMedia(text, file) {
        let out = text;
        const uploads = [];
        const matches = Array.from(text.matchAll(IMAGE_EMBED));
        for (const m of matches) {
            const [md, linkPath, size] = m;
            const imageFile = this.app.metadataCache.getFirstLinkpathDest(linkPath, file.path);
            if (!(imageFile instanceof obsidian.TFile))
                continue;
            let dataBase64 = '';
            let MathRandom = Math.floor(Math.random() * 10000000);
            let ankiFileName = imageFile.name;
            const windowAsAny = window;
            const isExcalidraw = windowAsAny.ExcalidrawAutomate && windowAsAny.ExcalidrawAutomate.isExcalidrawFile(imageFile);
            if (isExcalidraw) {
                try {
                    const ea = windowAsAny.ExcalidrawAutomate;
                    // Scale 1.5 usually provides a good balance between quality and file size
                    const blob = await ea.createPNG(imageFile.path, 1.5);
                    const arrayBuffer = await blob.arrayBuffer();
                    dataBase64 = obsidian.arrayBufferToBase64(arrayBuffer);
                    ankiFileName = `${imageFile.basename}_${MathRandom}.png`;
                }
                catch (e) {
                    console.error('Simple Anki Sync: Failed to generate PNG from Excalidraw file', e);
                    // Fallback to reading the binary directly (which will be broken in Anki, but prevents a total crash)
                    const buffer = await this.app.vault.readBinary(imageFile);
                    dataBase64 = obsidian.arrayBufferToBase64(buffer);
                }
            }
            else {
                const buffer = await this.app.vault.readBinary(imageFile);
                dataBase64 = obsidian.arrayBufferToBase64(buffer);
            }
            uploads.push({
                ankiFileName,
                dataBase64,
            });
            // Anki requires URL encoding for filenames with spaces in the img src tag
            const encodedFileName = encodeURIComponent(ankiFileName);
            const tag = size
                ? `<img src="${encodedFileName}" width="${size}">`
                : `<img src="${encodedFileName}">`;
            out = out.replace(md, tag);
        }
        return { content: out, mediaToUpload: uploads };
    }
    convertLatexDelimiters(text) {
        let tmp = text.replace(BLOCK_LATEX, '\\[$1\\]');
        return tmp.replace(INLINE_LATEX, '\\($1\\)');
    }
    convertMarkdownBoldToHtml(text) {
        // Convert Markdown bold (**text**) to HTML bold (<b>text</b>)
        return text.replace(/\*\*(.*?)\*\*/g, '<b>$1</b>');
    }
    async syncFile(file, silent = false) {
        var _a;
        // Check AnkiConnect availability before syncing
        if (!(await this.anki.verifyConnection())) {
            new obsidian.Notice('AnkiConnect is not available. Please make sure Anki is running and AnkiConnect is installed.');
            return [];
        }
        if (!silent)
            new obsidian.Notice(`Syncing ${file.basename}...`);
        const orig = await this.app.vault.read(file);
        const { notes, deckName } = this.parseNotesFromContent(orig, file);
        if (!deckName) {
            if (!silent)
                new obsidian.Notice(`No #anki/deck tag found in ${file.basename}. Skipping.`);
            return [];
        }
        await this.anki.createDeck(deckName);
        const existingIds = [];
        for (const m of orig.matchAll(NOTE_ID_COMMENT_GLOBAL))
            existingIds.push(+m[1]);
        const lines = orig.split('\n');
        const newIds = [];
        for (const note of notes) {
            // Media
            const frontMed = await this.processMedia(note.front, file);
            const backMed = await this.processMedia(note.back, file);
            for (const u of [...frontMed.mediaToUpload, ...backMed.mediaToUpload]) {
                await this.anki.storeMediaBase64(u.ankiFileName, u.dataBase64);
            }
            // LaTeX
            let frontHtml = this.convertLatexDelimiters(frontMed.content);
            let backHtml = this.convertLatexDelimiters(backMed.content);
            // Convert Markdown bold to HTML bold
            frontHtml = this.convertMarkdownBoldToHtml(frontHtml);
            backHtml = this.convertMarkdownBoldToHtml(backHtml);
            // Obsidian-Link
            const vault = this.app.vault.getName();
            let url = '';
            if (note.noteId) {
                url = `obsidian://simple-anki-sync?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(file.path)}&noteId=${note.noteId}`;
            }
            else {
                url = `obsidian://open?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(file.path)}`;
            }
            backHtml += `<br><small><a href="${url}" style="text-decoration:none;color:grey;font-size:0.8em;">Obsidian Note</a></small>`;
            const fields = { Front: frontHtml, Back: backHtml };
            if (note.noteId) {
                await this.anki.updateNote(note.noteId, fields);
                newIds.push(note.noteId);
                const info = await this.anki.fetchCardInfo([note.noteId]);
                if (((_a = info[0]) === null || _a === void 0 ? void 0 : _a.deckName) !== deckName) {
                    await this.anki.changeDeck([note.noteId], deckName);
                }
            }
            else {
                const created = await this.anki.addNote(deckName, DEFAULT_MODEL, fields);
                if (created) {
                    newIds.push(created);
                    const dataRowIndex = note.startLine + 2;
                    const updatedRow = this.appendNoteIdToRow(lines[dataRowIndex], created);
                    lines[dataRowIndex] = updatedRow;
                    // Replace the fallback URL with the precise custom protocol URL now that we have an ID
                    const newUrl = `obsidian://simple-anki-sync?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(file.path)}&noteId=${created}`;
                    const updatedBackHtml = backHtml.replace(url, newUrl);
                    await this.anki.updateNote(created, { Front: frontHtml, Back: updatedBackHtml });
                }
            }
        }
        // Remove old IDs and Anki-Cards
        const toDelete = existingIds.filter(id => !newIds.includes(id));
        if (toDelete.length) {
            await this.anki.deleteNotes(toDelete);
            for (const id of toDelete) {
                for (let idx = lines.length - 1; idx >= 0; idx--) {
                    const result = this.stripNoteIdFromLine(lines[idx], id);
                    if (!result.removed)
                        continue;
                    if (result.removeLine) {
                        lines.splice(idx, 1);
                    }
                    else {
                        lines[idx] = result.updatedLine;
                    }
                }
            }
        }
        const updated = lines.join('\n');
        if (updated !== orig) {
            await this.app.vault.modify(file, updated);
        }
        if (!silent)
            new obsidian.Notice(`${file.basename} synced.`);
        return newIds;
    }
    async syncVault() {
        // Check AnkiConnect availability before vault sync
        if (!(await this.anki.verifyConnection())) {
            new obsidian.Notice('AnkiConnect is not available. Please make sure Anki is running and AnkiConnect is installed.');
            return;
        }
        new obsidian.Notice('Starting vault sync. This may take a while...');
        const files = this.app.vault.getMarkdownFiles();
        for (const f of files) {
            try {
                await this.syncFile(f, true);
            }
            catch (e) {
                console.error(`Error in vault sync for ${f.path}:`, e);
                new obsidian.Notice(`Error syncing ${f.basename}. See console for Details.`);
            }
        }
        new obsidian.Notice('Vault sync complete.');
    }
    async unSyncFile(file, silent = false) {
        // Check AnkiConnect availability before syncing
        if (!(await this.anki.verifyConnection())) {
            new obsidian.Notice('AnkiConnect is not available. Please make sure Anki is running and AnkiConnect is installed.');
            return;
        }
        if (!silent)
            new obsidian.Notice(`Unsyncing ${file.basename}...`);
        const orig = await this.app.vault.read(file);
        const existingIds = [];
        for (const m of orig.matchAll(NOTE_ID_COMMENT_GLOBAL))
            existingIds.push(+m[1]);
        const lines = orig.split('\n');
        // Remove all IDs and Anki-Cards
        if (existingIds.length) {
            await this.anki.deleteNotes(existingIds);
            const cleaned = [];
            for (const line of lines) {
                const result = this.stripNoteIdFromLine(line);
                if (result.removeLine) {
                    continue;
                }
                cleaned.push(result.updatedLine);
            }
            lines.length = 0;
            lines.push(...cleaned);
        }
        const updated = lines.join('\n');
        if (updated !== orig) {
            await this.app.vault.modify(file, updated);
        }
        if (!silent)
            new obsidian.Notice(`${file.basename} successfully unsynced`);
        return;
    }
}

module.exports = SimpleAnkiSyncPlugin;
//# sourceMappingURL=main.js.map

/* nosourcemap */